### ISSUE TITLE
Exclude some apps

### ISSUE THREAD

**Issue by rayman3003** [vpnhood/VpnHood#367] opened 2023-08-12 11:18 UTC
Is it possible to add an option, so we can exclude some apps in the settings of VPNHood, so those apps would not use vpn.

For example, add executables of apps (for example firefox.exe) to the exclusion list of VPNhood, and then those app connect to internet, without VPN access.

**Comment by trudyhood** [comment] 2023-08-13 19:07
Not supported at the moment. Please check this:
duplicate of #270

**Closed by trudyhood** 2023-08-13 19:07 UTC
