### ISSUE TITLE
Handling Multiple IPs for a Single Domain in Configuration

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#524] opened 2024-04-25 22:58 UTC
I am considering configuring VPNHood with a domain name that resolves to multiple IP addresses. Could you clarify how VPNHood manages this scenario? Specifically, I'd like to understand:

1. Whether the domain name resolution and traffic routing to multiple IPs are managed by the OS or directly by the VPNHood application.
2. What happens if the initially resolved IP is not available - does VPNHood automatically attempt to connect to the next available IP?
3. The interval after which VPNHood issues a new DNS request (after the TTL, or only when the client tries to reconnect).

Thank you for any insights or guidance on this configuration.

**Comment by trudyhood** [comment] 2024-04-26 05:23
Hi,

1. VpnHood does not route traffic to multiple IPs; each session is bound to a single IP at the moment.
2. Duplicate of #490 
3. Only when the client tries to reconnect

VpnHood is a hybrid VPN, some kind of SOCKS proxy, and packet routing depends on configuration.

**Closed by trudyhood** 2024-04-26 05:23 UTC

**Comment by trudyhood** [comment] 2024-07-15 20:37
it is done
