### ISSUE TITLE
problem with VPN Hood server non root

### ISSUE THREAD

**Issue by armin567ip** [vpnhood/VpnHood#361] opened 2023-08-01 18:49 UTC
Hi man. I have posted an issue long ago about this problem but I guess I couldn't really explain it well so you didn't take it seriously and do anything.
So let me explain again.
There is a problem when running VPNHood server without root.
If we start deploying VPNHood on Linux without root according to the Wiki. 
Step 3 is to start the server which is this command "./VpnHoodServer"
But when I enter this command it will show "Server is ready!" but the problem is that the terminal will kinda get locked so I can not type anything. I will not be able to do step 4 which is generating an access key. I have to press Ctrl + C to release than thing. and the important thing is if I release that thing. VPN hood will not work. i either tried opening another terminal and generating the access key from that. but the problem is. when the first terminal is closed VPN hood will not work. this is a problem and have to be fixed.

**Comment by trudyhood** [comment] 2023-08-01 20:02
> but the problem is. when the first terminal is closed VPN hood will not work. this is a problem and have to be fixed.
duplicate of #345 

I did take it seriously and recommended you check this page. The discussion is about how to keep an app working after closing the putty. it is what you need, unfortunately fixing by code is not so easy for us. I hope you can sort it out.
https://superuser.com/questions/96660/how-can-i-keep-a-process-alive-after-closing-the-putty-session

![image](https://github.com/vpnhood/VpnHood/assets/72891124/bb053fbf-f5cf-45e4-a9df-9c1c1291e9a8)

**Closed by trudyhood** 2023-08-01 20:02 UTC

**Comment by armin567ip** [comment] 2023-08-01 21:27
> > but the problem is. when the first terminal is closed VPN hood will not work. this is a problem and have to be fixed.
> duplicate of #345 
> 
> I did take it seriously and recommended you check this page. The discussion is about how to keep an app working after closing the putty. it is what you need, unfortunately fixing by code is not so easy for us. I hope you can sort it out.
> https://superuser.com/questions/96660/how-can-i-keep-a-process-alive-after-closing-the-putty-session
> 
> ![image](https://github.com/vpnhood/VpnHood/assets/72891124/bb053fbf-f5cf-45e4-a9df-9c1c1291e9a8)
> 

Thanks man, I could get it to work.
I would also like to report one issues about the Android app. If you hold your finger on the texts . For example VpnHood!. It will select that text. And you have to fix it . It shouldnt be selectable![Screenshot_20230802-005656_VpnHood!.jpg](https://github.com/vpnhood/VpnHood/assets/106415257/e2791bb9-a8cb-409d-87d4-d210be756758)

**Comment by trudyhood** [comment] 2023-08-01 21:43
Thank you for reporting this. I have added to task list
