### ISSUE TITLE
client app for linux

### ISSUE THREAD

**Issue by arashammm** [vpnhood/VpnHood#311] opened 2023-04-01 01:18 UTC
hello there
I just wanted to know is there any way to configure a client app for the linux with the current developments?
it would give many more flexiblibilty to the stack and more configuration possibilities.

**Comment by trudyhood** [comment] 2023-04-01 07:52
Hi, please see the following discussion
Duplicate of #302

**Closed by trudyhood** 2023-04-01 07:52 UTC
