### ISSUE TITLE
how to share VPNHOOD in hotspot lapotop

### ISSUE THREAD

**Issue by delshad1522** [vpnhood/VpnHood#371] opened 2023-08-19 11:35 UTC
hello dear
how to share VPNHOOD in hotspot lapotop for other devices ???

**Comment by delshad1522** [comment] 2023-08-19 11:36
or set in modem or roter ???

**Comment by trudyhood** [comment] 2023-08-19 23:24
Sorry, this feature is not available. We did some work on it but left it due to some other priority.
Duplicate of #118

**Closed by trudyhood** 2023-08-19 23:24 UTC
