### ISSUE TITLE
 It does not automatically activate the public ip and does not let me connect outside the network.

### ISSUE THREAD

**Issue by Keiser04** [vpnhood/VpnHood#522] opened 2024-04-23 13:05 UTC
![image](https://github.com/vpnhood/VpnHood/assets/146493916/85c9d6f2-6451-4e21-82d5-e6265621fb19)
Log ID:
[log.txt](https://github.com/vpnhood/VpnHood/files/15077264/log.txt)

**Comment by Keiser04** [comment] 2024-04-23 17:11
@trudyhood is the problem I mentioned yesterday

**Comment by trudyhood** [comment] 2024-04-23 18:37
are you sure your server is running and 2a01:***:0007:443 is reachable? make sure the 443 port is open by your network firewall

**Comment by Keiser04** [comment] 2024-04-23 21:34
A connection cannot be established as the target machine explicitly denied such a connection. it sey

**Comment by Keiser04** [comment] 2024-04-23 21:36
![image](https://github.com/vpnhood/VpnHood/assets/146493916/e7c8bbee-966a-462f-a3a3-47a703d1a234)
and yes i have the port open on router, or dym in the server?

**Comment by trudyhood** [comment] 2024-04-23 21:47
I am not familiar with this console. The key is simple. The public endpoint in your token (IP:port) should be mapped to server listener EndPoint (IP:port)

![image](https://github.com/vpnhood/VpnHood/assets/72891124/52378e66-4562-44eb-893b-f1f315c1c62d)

This configuration is for servers where the local IP and port differ from the public IP. Also, make sure that your server is listening to an IP that can reach from the public network. The configuration is exactly like conventional web servers. VpnHood behaves exactly like a webserver; if you can set up a webserver, you should be able to set up VpnHood too.

**Comment by trudyhood** [comment] 2024-04-23 21:50
If clients fail to connect randomly, it may indicate that the local endpoint is set to "Public". In such cases, the client will be redirected to that IP by a random server. Therefore, it is important to ensure that all server private IPs that are not reachable from outside are marked as private.

**Comment by Keiser04** [comment] 2024-04-23 22:43
i am using automatic mode 
![image](https://github.com/vpnhood/VpnHood/assets/146493916/101bfc3f-7bac-4b0b-bf21-af54cc6af673)

**Comment by Keiser04** [comment] 2024-04-23 22:44
ok i think is poblem of firewire

**Comment by Keiser04** [comment] 2024-04-23 22:46
idk why if i dont touch it but i will try if is all rigth

**Comment by trudyhood** [comment] 2024-04-24 01:31
Could you fix the issue?

**Comment by Keiser04** [comment] 2024-04-24 01:35
> Could you fix the issue?

I thought it was but I tried to connect from my mobile using data and I get network is unreacheble.

**Comment by Keiser04** [comment] 2024-04-24 01:36
i just send a report

58cc16ce@20240424T013551-93250714

@trudyhood

**Comment by trudyhood** [comment] 2024-04-24 01:37
Make sure the mobile network does not block your IP. Can you give me an access key? trudy@vpnhood.com

**Comment by Keiser04** [comment] 2024-04-24 01:38
I'm going to sleep in 10 minutes but I've already sent it to you.

**Comment by trudyhood** [comment] 2024-04-24 01:45
Are you sure you have IPv6 on your client? 😄 
You have just configured IPv6, I could connect to your server via the IpV6 network, but when the client does not have IPv6, they will get such the error:
Se ha intentado una operación de socket en una red no accessible (Network Unreachable)

Many home users still do not have IPv6.

**Comment by Keiser04** [comment] 2024-04-24 01:46
How do I make it go with those who have ipv4?

**Comment by Keiser04** [comment] 2024-04-24 01:46
tomorrow I will try with the laptop out of network but it's the same problem I had before and I'm sorry about that.

**Comment by Keiser04** [comment] 2024-04-24 01:48
ah it could be because i am in data because in lan if it lets me. but there is the question i don't know if it is because of lan or because of mobile data. I will open again tomorrow if the problem persists.

**Comment by trudyhood** [comment] 2024-04-24 01:52
> How do I make it go with those who have ipv4?

You need to configure your server with IPv4 the same as you did for IPv6.

**Comment by Keiser04** [comment] 2024-04-24 02:02
The thing is that I don't touch anything. It is in automatic. It used to
add the public ip4 but it doesn't add it anymore.

**Comment by trudyhood** [comment] 2024-04-24 04:56
Oh I got it. 
The problem is using my-ip.io to resolve IP addresses. Perhaps you restart your servers too many times and remove endpoints at some point. They throttle the use of their services, so they may stop replying to your server's IPv6 address. 
I suggest disabling "Auto Configuration," manually setting the IP, and then enabling "Auto Configuration" again. Let me know if this resolves the issue.

**Comment by Keiser04** [comment] 2024-04-24 12:53
this problem i have: A socket operation was attempted on an unreachable network.
I am in windows 11,
bdd856c0@20240424T125037-60154552

**Comment by trudyhood** [comment] 2024-04-24 21:23
> this problem i have: A socket operation was attempted on an unreachable network. I am in windows 11, bdd856c0@20240424T125037-60154552

Perhaps your Windows client does not have ipv6. Have you configured ipv4?

**Comment by Keiser04** [comment] 2024-04-24 22:30
![image](https://github.com/vpnhood/VpnHood/assets/146493916/f5ca97ef-4972-4c6a-a40c-52f2874baf4b)
in local i can acces

**Comment by Keiser04** [comment] 2024-04-24 23:30
> > this problem i have: A socket operation was attempted on an unreachable network. I am in windows 11, bdd856c0@20240424T125037-60154552
> 
> Perhaps your Windows client does not have ipv6. Have you configured ipv4?

![image](https://github.com/vpnhood/VpnHood/assets/146493916/a7a597a3-af47-44b2-b591-b1439113ffb0)
but i have ip6

**Comment by trudyhood** [comment] 2024-04-25 02:07
can you open these sites on your windows 11:

https://ipv6test.google.com/
https://test-ipv6.com/

**Closed** 2024-04-28 16:24 UTC
Labels: Waiting for info
