### ISSUE TITLE
2022/12/21 00:45:35.941 | Error |  | Server  TcpHost Could not AcceptTcpClient. System.Net.Sockets.SocketException An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by joephalex** [vpnhood/VpnHood#217] opened 2022-12-21 09:23 UTC
Hi,

I have had this issue whereby after while the server through this error 
2022/12/21 00:45:35.941 | Error |  | Server
 TcpHost Could not AcceptTcpClient. System.Net.Sockets.SocketException An existing connection was forcibly closed by the remote host.

The moment this issue occurs all the connection get disconnected and it does not receive any new connections.

Please advice me, I am ruining on windows 2019server 

Thank you

**Comment by trudyhood** [comment] 2022-12-21 09:25
Can you send me the full log file?

**Comment by joephalex** [comment] 2022-12-21 09:32
Sure I will send it to you. May I have your email please?

**Comment by trudyhood** [comment] 2022-12-21 09:33
support@vpnhood.com

**Comment by joephalex** [comment] 2022-12-21 09:42
Hi,

I have send the log to your email. Kindly check.

Thank you for your all efforts

**Comment by titancomputer** [comment] 2022-12-21 09:47
Hello
i can confirm this bug or issue.
i've been setup 2 days ago on windows server 2019 and after somewhile the server goes down and i see that error on topic title.

full log : 
2022-12-21 10:50:05.9216 | Info |  | Server 
 VpnHood.Server, Version=2.6.328.0, Culture=neutral, PublicKeyToken=null  

2022-12-21 10:50:05.9757 | Info |  | Server 
 OS: Windows 10.0.17763, TotalMemory: 6 GB, Logical Cores: 4  

2022-12-21 10:50:05.9757 | Info |  | Server 
 MinWorkerThreads: 4, MinCompletionPortThreads: 30, MaxWorkerThreads: 32767, MaxCompletionPortThreads: 32767,   

2022-12-21 10:50:05.9757 | Info |  | Server 
 Configuring by the Access Server...  

2022-12-21 10:50:07.4852 | Info |  | Server 
 ServerConfig: {"Tracking":{"TrackClientIp":false,"TrackLocalPort":false,"TrackDestinationIp":false,"TrackDestinationPort":false},"TrackingOptions":{"TrackClientIp":false,"TrackLocalPort":false,"TrackDestinationIp":false,"TrackDestinationPort":false},"Session":{"Timeout":"00:10:00","UdpTimeout":"00:01:00","TcpTimeout":"00:15:00","IcmpTimeout":"00:00:30","SyncCacheSize":100000000,"SyncInterval":"00:20:00","MaxDatagramChannelCount":8,"MaxUdpPortCount":0,"TcpBufferSize":8192},"SessionOptions":{"Timeout":"00:10:00","UdpTimeout":"00:01:00","TcpTimeout":"00:15:00","IcmpTimeout":"00:00:30","SyncCacheSize":100000000,"SyncInterval":"00:20:00","MaxDatagramChannelCount":8,"MaxUdpPortCount":0,"TcpBufferSize":8192},"UdpPort":0,"ConfigCode":"00000000-0000-0000-0000-000000000000","TcpEndPoints":["0.0.0.0:5892"],"UpdateStatusInterval":"00:02:00"}  

2022-12-21 10:50:07.4852 | Info |  | Server 
 Starting TcpHost...  

2022-12-21 10:50:07.4852 | Info |  | Server 
 Start listening on 0.0.0.0:5892  

2022-12-21 10:50:07.4921 | Info |  | Server 
 Set UpdateStatusInterval to 120 seconds.  

2022-12-21 10:50:07.4921 | Info |  | Server 
 Server is ready!  

2022-12-21 11:11:01.0921 | Info | Session | Server => RemoteEp: 151.*.*.18:10918 
 Processing hello request... ClientEp: 151.*.*.18:10918  

2022-12-21 11:11:01.1029 | Info | Session | Server => RemoteEp: 151.*.*.18:10918 
 Creating SessionOptions... TokenId: **-84cf-f28e0e04d7db, ClientId: **-a2fb-ca37758926c6, ClientVersion: 2.6.326  

2022-12-21 11:11:01.1197 | Info | Session | Server => RemoteEp: 151.*.*.18:10918 
 New session has been created. SessionId: 1  

2022-12-21 11:11:03.1068 | Info | Session | Server => RemoteEp: 151.*.*.18:10961 
 Processing hello request... ClientEp: 151.*.*.18:10961  

2022-12-21 11:11:03.1068 | Info | Session | Server => RemoteEp: 151.*.*.18:10961 
 Creating SessionOptions... TokenId: **-84cf-f28e0e04d7db, ClientId: **-a2fb-ca37758926c6, ClientVersion: 2.6.326  

2022-12-21 11:11:03.1068 | Info | Session | Server => RemoteEp: 151.*.*.18:10961 
 New session has been created. SessionId: 2  

2022-12-21 11:21:05.8763 | Info | Session |  
 The session has been temporary closed. SessionId: 1.  

2022-12-21 11:50:21.6630 | Info | Session | Server => RemoteEp: 89.*.*.148:34603 
 Processing hello request... ClientEp: 89.*.*.148:34603  

2022-12-21 11:50:21.6630 | Info | Session | Server => RemoteEp: 89.*.*.148:34603 
 Creating SessionOptions... TokenId: **-b77e-cdb3a5035a02, ClientId: **-aca6-a7b098a76604, ClientVersion: 2.6.326  

2022-12-21 11:50:21.6760 | Info | Session | Server => RemoteEp: 89.*.*.148:34603 
 New session has been created. SessionId: 3  

2022-12-21 11:53:40.7842 | Info | Session | Server => RemoteEp: 2.*.*.40:23755 => SessionId: 3 
 The session have been closed by the access server. ErrorCode: SessionClosed  

2022-12-21 11:53:40.7842 | Info | Session | Server => RemoteEp: 2.*.*.40:23755 => SessionId: 3 
 The session has been permanently closed. SessionId: 3.  

2022-12-21 12:12:19.4590 | Info | Session | Server => RemoteEp: 89.*.*.240:43149 
 Processing hello request... ClientEp: 89.*.*.240:43149  

2022-12-21 12:12:19.4590 | Info | Session | Server => RemoteEp: 89.*.*.240:43149 
 Creating SessionOptions... TokenId: **-b77e-cdb3a5035a02, ClientId: **-aca6-a7b098a76604, ClientVersion: 2.6.326  

2022-12-21 12:12:19.4590 | Info | Session | Server => RemoteEp: 89.*.*.240:43149 
 New session has been created. SessionId: 4  

2022-12-21 12:33:42.8111 | Info | Session | Server => RemoteEp: 2.*.*.122:6350 
 Processing hello request... ClientEp: 2.*.*.122:6350  

2022-12-21 12:33:42.8111 | Info | Session | Server => RemoteEp: 2.*.*.122:6350 
 Creating SessionOptions... TokenId: **-b77e-cdb3a5035a02, ClientId: **-aca6-a7b098a76604, ClientVersion: 2.6.326  

2022-12-21 12:33:42.8158 | Info | Session | Server => RemoteEp: 2.*.*.122:6350 
 New session has been created. SessionId: 5  

2022-12-21 12:44:05.8702 | Info | Session |  
 The session have been closed by the access server. ErrorCode: SessionSuppressedBy  

2022-12-21 12:44:05.8702 | Info | Session |  
 The session has been temporary closed. SessionId: 4.  

2022-12-21 12:47:33.1223 | Info | Session | Server => RemoteEp: 151.*.*.18:10961 
 The session have been closed by the access server. ErrorCode: AccessError  

2022-12-21 12:49:05.8726 | Info | Session |  
 The session has been temporary closed. SessionId: 5.  

2022-12-21 12:50:51.3332 | Info | Session | Server => RemoteEp: 151.*.*.18:12742 
 Processing hello request... ClientEp: 151.*.*.18:12742  

2022-12-21 12:50:51.3332 | Info | Session | Server => RemoteEp: 151.*.*.18:12742 
 Creating SessionOptions... TokenId: **-84cf-f28e0e04d7db, ClientId: **-a2fb-ca37758926c6, ClientVersion: 2.6.326  

2022-12-21 12:50:51.3332 | Info | Session | Server => RemoteEp: 151.*.*.18:12742 
 New session has been created. SessionId: 6  

2022-12-21 12:55:17.6920 | Error |  | Server 
 TcpHost Could not AcceptTcpClient. System.Net.Sockets.SocketException An existing connection was forcibly closed by the remote host. 

2022-12-21 12:55:17.6920 | Info |  | Server 
 Stop listening on 0.0.0.0:5892

**Comment by trudyhood** [comment] 2022-12-21 09:57
I catch the bug.  It will be solved in the next Version. 

I can also see a bug in our Windows vhupdate too. TaskScheduler can not run it but it can run from the command line. Can you guys find the issue?

**Comment by titancomputer** [comment] 2022-12-21 10:04
thanks for responding.

i see this on powershell :
PS C:\Users\Administrator> powershell.exe -NonInteractive -NoLogo -NoProfile -File "C:\Program Files/VpnHood/VpnHoodServer/vhupdate.ps1" -q
Updating VpnHood Server for Windows...
Installed version: 2.6.328
Latest version: 2.6.328
The installed version is up to date.

when i run task scheduler i can't see log or something?
maybe because its the latest version?

**Comment by trudyhood** [comment] 2022-12-21 10:08
@titancomputer 
> when i run task scheduler i can't see log or something?

That's my problem, too 😕 
It looks like the scheduler can't run it properly on some computers. It must be updated if you open publish.json and decrease the version property.

**Comment by titancomputer** [comment] 2022-12-21 10:44
> @titancomputer
> 
> > when i run task scheduler i can't see log or something?
> 
> That's my problem, too 😕 It looks like the scheduler can't run it properly on some computers. It must be updated if you open publish.json and decrease the version property.

change the user/groups on your task  from SYSTEM to Administrators and done.

**Comment by trudyhood** [comment] 2022-12-21 11:06
I cannot use Administrator in setup. Perhaps local network or something else.

**Comment by titancomputer** [comment] 2022-12-21 14:51
> I cannot use Administrator in setup. Perhaps local network or something else.

i think this is privilege issue, but i can't solve that.

i look for this problem and i found a way to get error logs.

you can find it [here](https://community.spiceworks.com/topic/2355649-task-scheduler-not-running-powershell-script#:~:text=Start%2DTranscript%20C%3A%5CWindows%5CTemp%5Creport.log%0A%3C%23%0AYOUR%20CODE%20HERE%0A%23%3E%0AStop%2DTranscript)

and i did that so i've get this log :

`**********************
Windows PowerShell transcript start
Start time: 20221221181838
Username: WORKGROUP\SYSTEM
RunAs User: WORKGROUP\SYSTEM
Configuration Name: 
Machine: (Microsoft Windows NT 10.0.17763.0)
Host Application: powershell.exe -NonInteractive -NoLogo -NoProfile -File C:\Program Files/VpnHood/VpnHoodServer/vhupdate.ps1 -q
Process ID: 6232
PSVersion: 5.1.17763.3770
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.3770
BuildVersion: 10.0.17763.3770
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\report.log
Updating VpnHood Server for Windows...
Installed version: 2.6.321
Latest version: 2.6.328
Installing the latest version...
PS>TerminatingError(Invoke-WebRequest): "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. "
>> TerminatingError(Invoke-WebRequest): "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. "
The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At C:\Program Files\VpnHood\VpnHoodServer\vhupdate.ps1:44 char:27
+ ... iptblock]::Create((Invoke-WebRequest($onlineInstallScriptUrl)))) -q - ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

**********************
Windows PowerShell transcript end
End time: 20221221181839
**********************
`

this problem happens when the os hasn't IE.

the solution is [here](https://stackoverflow.com/questions/38005341/the-response-content-cannot-be-parsed-because-the-internet-explorer-engine-is-no#:~:text=%24rss%20%3D%20Invoke%2DWebRequest%20%2DUri%20%24url%20%2DUseBasicParsing) but i can't implement that.

**Comment by joephalex** [comment] 2022-12-21 15:33
During my first install last time I saw this error "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete." 

I did open IE and and there was a popup for asking to apply default settings and I just selected "use recommended security and compatibility settings"
![IE](https://user-images.githubusercontent.com/106926244/208942733-df27a201-df1c-41ce-8a6b-629670badd85.png)

**Comment by titancomputer** [comment] 2022-12-21 16:19
> During my first install last time on my PC I saw this error "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete."
> 
> I did open IE and and there was a popup for asking to apply default settings and I just selected "use recommended security and compatibility settings"
> 
> I did open IE on the server and I did apply the same right now. Do you think it may solve the problem? ![IE](https://user-images.githubusercontent.com/106926244/208942733-df27a201-df1c-41ce-8a6b-629670badd85.png)

not worked for me, after that windows server 2022 hasn't IE.

**Comment by titancomputer** [comment] 2022-12-21 16:42
how can i downgrade version untill you fix this issue?

**Comment by trudyhood** [comment] 2022-12-21 19:25
I fixed that, and we will release a new version soon. Thank you for your contribution.
Now I use Invoke-RestMethod instead Invoke-WebRequest. It looks like Invoke-WebRequest uses the browser

**Comment by trudyhood** [comment] 2022-12-21 20:46
We launched a new version 329. Please install it manually as the auto-update of the previous version didn't work. Let me know if there is any more issue.

**Closed by trudyhood** 2022-12-21 20:46 UTC

**Comment by joephalex** [comment] 2022-12-22 13:44
> We launched a new version 329. Please install it manually as the auto-update of the previous version didn't work. Let me know if there is any more issue.

Will do. Thank you again for your for this great project :)
