### ISSUE TITLE
Linux Client

### ISSUE THREAD

**Issue by AliKhadivi** [vpnhood/VpnHood#132] opened 2022-09-24 20:22 UTC

**Comment by trudyhood** [comment] 2022-09-25 07:46
Sorry, there is no plan for Linux Client yet. However, VpnHood is very portable, it just needed a packet, and other parts are ready.

**Comment by AliKhadivi** [comment] 2022-09-27 06:01
A package like WinDivert but for Linux?

**Comment by AliKhadivi** [comment] 2022-09-27 06:04
You can use it https://github.com/dotpcap/sharppcap
Supported Windows, Linux and Mac

**Comment by trudyhood** [comment] 2022-09-27 21:40
> You can use it https://github.com/dotpcap/sharppcap Supported Windows, Linux and Mac

We already use sharppcap, just need someone to implement and test a LinuxDevice same as the following project. It is isolated from the rest of VpnHood
https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Client.Device.WinDivert

Unfortunately, it is not our priority list.

**Comment by trudyhood** [comment] 2022-09-29 19:17
Duplicate of #113

**Closed by trudyhood** 2022-09-29 19:17 UTC
