### ISSUE TITLE
Required ports

### ISSUE THREAD

**Issue by esi-th** [vpnhood/VpnHood#306] opened 2023-03-25 21:21 UTC
To configure servers and install VPNhood, which ports need to be open? I am using the Vultr company service and I need to manually open the ports.

I configured it once with ADSL and it worked, but I didn't get any response with mobile data.

**Comment by AliKhadivi** [comment] 2023-03-26 07:45
Duplicate of #127 
The default is TCP 443. And if you want to use UDP mode, you need to open all UDP ports. You can specify the port of the server in command line too

**Closed** 2023-03-27 23:29 UTC
