### ISSUE TITLE
VpnHood Site-To-Site

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#284] opened 2023-02-27 15:45 UTC
Hi.
Is there possible to connect two different VpnHood Servers?
I need something like IPSec site-to-site Vpn on VpnHood.
It is really important for breaking filtering in some countries like of Iran or China.

**Comment by trudyhood** [comment] 2023-02-28 07:30
duplicate of #285

**Closed by trudyhood** 2023-02-28 07:30 UTC
