### ISSUE TITLE
Add domain name to network 

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#441] opened 2024-01-11 03:15 UTC
![VpnHoodDomain](https://github.com/vpnhood/VpnHood/assets/14541559/d4ae1eda-06f8-4ede-a13d-37bd6ac0d96e)

Hi, As you might remember we used one server in Iran to reroute traffic to our original VpnHood server which is located outside of Iran, is it possible to set domain name instead of IP Address inside of indicated rectangle? And make that as public token in way my clients just see a part of our domain name in client apps?

**Comment by trudyhood** [comment] 2024-01-12 07:46
First, keep your IP the same as before. Then, you can set your domain on the Server Farm page.

Check this:
Duplicate of #418

**Closed by trudyhood** 2024-01-12 07:46 UTC
