### ISSUE TITLE
Add flag for installing to a different port than 443

### ISSUE THREAD

**Issue by mfat** [vpnhood/VpnHood#494] opened 2024-03-30 11:54 UTC
The configuration file is too complicated. Please add a switch in the install script so that i can install to another port.

**Comment by trudyhood** [comment] 2024-03-30 21:50
It is not in the install script. You need to use appsettings.json 
I recommend you check the VpnHood Access Server, too, for more enterprise features.
[http](https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server)

duplicate of #495

**Closed by trudyhood** 2024-03-30 21:50 UTC
